### ISSUE TITLE
Ceph at a Glance dashboard is not the default at login

### ISSUE THREAD

**Issue by pcuzner** [ceph/cephmetrics#193]
After the latest test rebuild, I logged in as admin and noticed that the home dashboard is not working. Looking at the play I can see that it's set, but the dashboard is not starred first..this is what dashUpdater did. Could you add a task that stars the dashboard, prior to making it the home dashboard?

http://docs.grafana.org/http_api/user/#star-a-dashboard

**Comment by zmc** [comment]
Starring actually isn't related here. What must have happened here is that the home dashboard setting was changed for the admin user on the rhs_demo cluster using the web UI. Setting it on the org level only affects users that haven't done this.

I can make it so that we set the home dashboard for the org *and* the admin user.

**Comment by pcuzner** [comment]
closing as resolved
